# Generated by Django 4.2.4 on 2023-11-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="end_trip",
            field=models.DateTimeField(blank=True, verbose_name="End Trip"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_trip",
            field=models.DateTimeField(blank=True, verbose_name="Start Trip"),
        ),
    ]
