# Generated by Django 4.2.4 on 2023-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/trip_images/"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/trip_images/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
