# Generated by Django 4.2.4 on 2023-10-28 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="end_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
