# Generated by Django 4.2.4 on 2023-11-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_trip_end_trip_alter_trip_start_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="end_trip",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Trip"),
        ),
    ]
